### ISSUE TITLE
Sonar fails to start with NoClassDefFoundError

### ISSUE THREAD

**Issue by radboud-asselman** [SandroLuck/SonarDelphi#9]
I have Sonar 6.7.3 on Windows 2016. I downloaded the release 0.3.4-beta but also the latest sources and compiled it. I put the jar in the download directory, restart Sonar. Sonar gives a stack trace and fails to start.

Can someone help?

Stacktrace:
java.lang.IllegalStateException: Fail to load plugin Delphi [delphi]
                at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
                at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:582)
                at org.sonar.server.platform.Platform.start(Platform.java:211)
                at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
                at org.sonar.server.platform.Platform.access$500(Platform.java:46)
                at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
                at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
                at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
                at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
                at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/CodeColorizerFormat
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClass(Unknown Source)
                at java.security.SecureClassLoader.defineClass(Unknown Source)
                at java.net.URLClassLoader.defineClass(Unknown Source)
                at java.net.URLClassLoader.access$100(Unknown Source)
                at java.net.URLClassLoader$1.run(Unknown Source)
                at java.net.URLClassLoader$1.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(Unknown Source)
                at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
                at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
                at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
                at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
                at org.sonar.plugins.delphi.DelphiPlugin.getExtensions(DelphiPlugin.java:99)
                at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
                at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:78)
                ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
                at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
                at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
                at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
                ... 25 common frames omitted
2018.06.11 09:02:17 INFO  web[][o.s.p.StopWatcher] Stopping process

**Comment by SandroLuck** [comment]
It only works with 5.6.1 old LTS version. At least I  only tried to get it running on 5.6.1, I'm currently not working with Delphi anymore
